
- title: 泰晓 RISC-V 实验箱 —— 配套公开课，集成 RISC-V 开发板、实验盘和各类外设
  permalink: https://www.bilibili.com/video/BV15N4y1W7ES/
  description: 即时开展 RISC-V 架构的 Linux 内核、嵌入式 Linux 与驱动开发相关实验。
  group: products

- title: Pocket Linux 系统盘 —— 免安装、即插即用 Linux 系统盘，已支持 Ubuntu,Deepin,Manjaro,Kali,Mint,Fedora
  permalink: https://www.bilibili.com/video/BV1Qg4y1Y7s3
  description: 可以在 64 位 X86 台式机、笔记本、macBook 上即插即用，能安装常见交流、影音、办公与开发软件，可以作为独立系统使用，也可以作为双系统使用，等。某宝检索 “泰晓 Linux” 即可。
  group: products

- title: Linux Lab 真盘 —— 免安装、即插即用 Linux 内核与系统实验盘，已支持 Ubuntu,Deepin,Manjaro,Kali,Mint,Fedora
  permalink: /linux-lab-disk
  description: 可以在 64 位 X86 台式机、笔记本、macBook 上即插即用，可以作为独立系统使用，也可以作为双系统使用，可用于学习汇编、C语言、Shell、Uboot、Linx 0.11、RVOS、Linux内核与嵌入式 Linux 系统等。某宝检索 “泰晓 Linux” 即可。
  group: products

- title: 《360° 剖析 Linux ELF》视频课程 —— Linux 程序员基本素养训练课
  permalink: https://www.cctalk.com/m/group/88089283
  description: 以程序格式 ELF 为切入点，通过实验的方式学习 Linux 程序链接、装载、运行与调试原理，由泰晓科技技术社区创始人授课。
  group: products

- title: Linux 知识星球 —— 泰晓科技 VIP 知识频道
  permalink: https://t.zsxq.com/uB2vJyF
  description: 专属 Linux 原创内容与工作机会；VIP 微信群与 20 位嘉宾老师；泰晓学院视频课程专属优惠券；其他福利和机会。
  group: products

- title: 泰晓学院 —— 泰晓科技技术社区视频课堂
  permalink: https://m.cctalk.com/inst/sh8qtdag
  description: 在社区原有文章类、开源项目类内容原创的基础上，增加视频这种内容表达方式，由社区一线技术工程师和老师主讲。
  group: products
